// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3C43GhIre1CMwXy0nDbqaRkWi20RHMpE',
    appId: '1:1067833453561:web:f4ab7fd472a0a648912b28',
    messagingSenderId: '1067833453561',
    projectId: 'cmsc23-todo-app-gademdem-c4l',
    authDomain: 'cmsc23-todo-app-gademdem-c4l.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-gademdem-c4l.appspot.com',
    measurementId: 'G-CHL9ZZY5G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUJWf_N9b3TzhQfpCAbA95DCCUnO-JryQ',
    appId: '1:1067833453561:android:b0867d845c485ed5912b28',
    messagingSenderId: '1067833453561',
    projectId: 'cmsc23-todo-app-gademdem-c4l',
    storageBucket: 'cmsc23-todo-app-gademdem-c4l.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWnxy5nk1O-u4VOnG9tWV7ti7fV-QaqhI',
    appId: '1:1067833453561:ios:c72f4b85f2eb010e912b28',
    messagingSenderId: '1067833453561',
    projectId: 'cmsc23-todo-app-gademdem-c4l',
    storageBucket: 'cmsc23-todo-app-gademdem-c4l.appspot.com',
    iosClientId: '1067833453561-jjbtllacnrohdta40kmjcuer70t79l24.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWnxy5nk1O-u4VOnG9tWV7ti7fV-QaqhI',
    appId: '1:1067833453561:ios:c72f4b85f2eb010e912b28',
    messagingSenderId: '1067833453561',
    projectId: 'cmsc23-todo-app-gademdem-c4l',
    storageBucket: 'cmsc23-todo-app-gademdem-c4l.appspot.com',
    iosClientId: '1067833453561-jjbtllacnrohdta40kmjcuer70t79l24.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
